name: Update

on:
  push:
    branches:
      - main

jobs:
  update:
    strategy:
      matrix:
        project:
          - 'mriduls/esssans'
    name: Update downstream projects
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
      # - run: echo "Update ${{ matrix.project }}"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.X'
      - run: pip install copier
      # - run: git checkout -b update_copier_actions
      - run: copier update --skip-answered --vcs-ref=HEAD
      # - run: git add .
      # - run: git commit -m "Update ${{ matrix.project }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6