name: Update

on:
  push:
    branches:
      - main

jobs:
  update:
    strategy:
      matrix:
        project:
          - 'mriduls/esssans'
    name: Update downstream projects
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.project }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.X'
      - run: pip install copier
      - run: copier update --skip-answered --vcs-ref=HEAD
      # - run: git add .
      # - run: git commit -m "Update ${{ matrix.project }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Sync ${{ matrix.project }} with copier template
          assignees: MridulS
